"""
==========================================================
MastiskhNet PDF Report Generator
==========================================================
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.units import inch


def generate_report(
    scan,
    statistics,
    output_dir,
):
    """
    Generate a professional PDF report.

    Parameters
    ----------
    scan : MRIScan
    statistics : dict
    output_dir : str

    Returns
    -------
    str
    """

    os.makedirs(output_dir, exist_ok=True)

    report_path = os.path.join(
        output_dir,
        "brain_tumor_report.pdf",
    )

    doc = SimpleDocTemplate(report_path)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    elements = []

    # =====================================================
    # TITLE
    # =====================================================

    elements.append(
        Paragraph(
            "MastiskhNet Brain Tumor Analysis Report",
            title_style,
        )
    )

    elements.append(Spacer(1, 0.35 * inch))

    # =====================================================
    # SCAN DETAILS
    # =====================================================

    scan_data = [
        ["Scan ID", str(scan.id)],
        ["Patient ID", str(scan.patient_id)],
        ["Doctor ID", str(scan.doctor_id)],
        ["Prediction Status", "Completed"],
        ["Generated Report", "Yes"],
    ]

    table = Table(scan_data, colWidths=[2.2 * inch, 3.5 * inch])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    elements.append(table)

    elements.append(Spacer(1, 0.4 * inch))

    # =====================================================
    # TUMOR STATISTICS
    # =====================================================

    elements.append(
        Paragraph(
            "<b>Tumor Statistics</b>",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 10))

    stats_table = [[
        "Tumor Type",
        "Voxels",
        "Volume (mm³)",
        "Volume (cm³)",
        "Percentage"
    ]]

    for tumor_type, values in statistics.items():

        stats_table.append(
            [
                tumor_type,
                str(values["voxels"]),
                f'{values["volume_mm3"]:.2f}',
                f'{values["volume_cm3"]:.2f}',
                f'{values["percentage"]:.2f}%',
            ]
        )

    table = Table(stats_table)

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )

    elements.append(table)

    elements.append(Spacer(1, 0.4 * inch))

    # =====================================================
    # CONCLUSION
    # =====================================================

    elements.append(
        Paragraph(
            "<b>Conclusion</b>",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 8))

    elements.append(
        Paragraph(
            "The MRI scan has been processed successfully using the "
            "MastiskhNet deep learning pipeline. The segmentation mask, "
            "3D tumor mesh, and quantitative tumor statistics have been "
            "generated automatically.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<i>This report was automatically generated by MastiskhNet.</i>",
            styles["Italic"],
        )
    )

    doc.build(elements)

    return report_path


def generate_patient_credentials_report(
    patient,
    doctor,
    temp_password,
    output_dir,
):
    """
    Generate an A4 PDF containing the project description
    and the patient's mobile app login credentials.

    Parameters
    ----------
    patient : User
    doctor : User
    temp_password : str
    output_dir : str

    Returns
    -------
    str
    """

    os.makedirs(output_dir, exist_ok=True)

    report_path = os.path.join(
        output_dir,
        f"patient_{patient.id}_credentials.pdf",
    )

    doc = SimpleDocTemplate(
        report_path,
        pagesize=A4,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    elements = []

    # =====================================================
    # TITLE
    # =====================================================

    elements.append(
        Paragraph(
            "MastiskhNet",
            title_style,
        )
    )

    elements.append(
        Paragraph(
            "AI-Powered Brain Tumor Detection &amp; Analysis System",
            styles["Heading3"],
        )
    )

    elements.append(Spacer(1, 0.3 * inch))

    # =====================================================
    # PROJECT DESCRIPTION
    # =====================================================

    elements.append(
        Paragraph(
            "MastiskhNet is an AI-powered clinical decision support platform "
            "that uses a deep learning model (Attention U-Net 3D) to analyze "
            "brain MRI scans, detecting, segmenting, and quantifying brain "
            "tumor regions. The system provides doctors with automated tumor "
            "segmentation, interactive 3D visualization, volumetric statistics, "
            "and detailed diagnostic reports to support clinical decision-making.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(
            "Through the MastiskhNet mobile application, patients can securely "
            "view their MRI analysis results, review their tumor segmentation "
            "and 3D models, communicate directly with their assigned doctor, "
            "and track their diagnostic history over time.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 0.35 * inch))

    # =====================================================
    # PORTAL ACCESS NOTE
    # =====================================================

    elements.append(
        Paragraph(
            "<b>Patient Portal Access</b>",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 8))

    elements.append(
        Paragraph(
            "A MastiskhNet mobile account has been created for you. Please "
            "download the MastiskhNet app and log in using the credentials "
            "below. For your security, please change your password "
            "immediately after your first login using the 'Change Password' "
            "option inside the app.",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 0.4 * inch))

    # =====================================================
    # CREDENTIALS TABLE (BOLD)
    # =====================================================

    details = [
        ["Patient Name:", patient.full_name],
        ["Date & Time of Visit:", datetime.now().strftime("%Y-%m-%d  %I:%M %p")],
        ["Doctor:", doctor.full_name],
        ["Mobile App Login ID (Email):", patient.email],
        ["Mobile App Temporary Password:", temp_password],
    ]

    table = Table(
        details,
        colWidths=[2.8 * inch, 3 * inch],
    )

    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    elements.append(table)

    elements.append(Spacer(1, 0.35 * inch))

    elements.append(
        Paragraph(
            "<i>Please keep this document confidential. Change your "
            "password immediately after your first login.</i>",
            styles["Italic"],
        )
    )

    doc.build(elements)

    return report_path