"""Add MRI slice viewer fields

Revision ID: 1da736cd9a7a
Revises: e011ec2dc486
Create Date: 2026-07-29 20:26:49.518304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da736cd9a7a'
down_revision: Union[str, Sequence[str], None] = 'e011ec2dc486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mri_scans', sa.Column('original_folder', sa.String(), nullable=True))
    op.add_column('mri_scans', sa.Column('segmentation_folder', sa.String(), nullable=True))
    op.add_column('mri_scans', sa.Column('overlay_folder', sa.String(), nullable=True))
    op.add_column('mri_scans', sa.Column('total_slices', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mri_scans', 'total_slices')
    op.drop_column('mri_scans', 'overlay_folder')
    op.drop_column('mri_scans', 'segmentation_folder')
    op.drop_column('mri_scans', 'original_folder')
    # ### end Alembic commands ###
