"""add region_stats to mri_scans

Revision ID: e011ec2dc486
Revises: 9891fe87496d
Create Date: 2026-07-26 09:26:52.003054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e011ec2dc486'
down_revision: Union[str, Sequence[str], None] = '9891fe87496d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mri_scans', sa.Column('region_stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mri_scans', 'region_stats')
    # ### end Alembic commands ###
