"""add mesh_glb_file to mri_scans

Revision ID: 9891fe87496d
Revises: 9bef40461caa
Create Date: 2026-07-25 19:35:30.039186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9891fe87496d'
down_revision: Union[str, Sequence[str], None] = '9bef40461caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mri_scans', sa.Column('mesh_glb_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mri_scans', 'mesh_glb_file')
    # ### end Alembic commands ###
