"""add mesh_material_file to mri_scans

Revision ID: 9bef40461caa
Revises: e05b6cc02ac3
Create Date: 2026-07-25 17:37:38.649920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bef40461caa'
down_revision: Union[str, Sequence[str], None] = 'e05b6cc02ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_reports_id'), table_name='medical_reports')
    op.drop_table('medical_reports')
    op.drop_column('chat_messages', 'is_read')
    op.add_column('mri_scans', sa.Column('mesh_material_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mri_scans', 'mesh_material_file')
    op.add_column('chat_messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('medical_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finding', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tumor_volume_mm3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tumor_volume_cm3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('report_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_reports_pkey'))
    )
    op.create_index(op.f('ix_medical_reports_id'), 'medical_reports', ['id'], unique=False)
    # ### end Alembic commands ###
